# Anchore configuration file


anchore_data_dir:  $HOME/anchore/

anchore_db_driver: 'AnchoreImageDB_FS'
anchore_db_driver_config:
  # only applicable to the 'anchore_image_db_fs' driver (default driver), path is relative to anchore_data_dir unless it is set to an abs path
  db_dir: 'anchore/anchore_image_db/test_db/data/data.db'

tmpdir: '/tmp'
log_file: '/anchore_logs/log_file.log'

debug_log_file: '/anchore_logs/debug_file.log'


image_data_store: 'data/'  # deprecated but still works - should use the anchore_db_driver_config + db_dir settings above to control location of anchore data

docker_conn: 'unix://var/run/docker.sock'
docker_conn_timeout: '120'

anchore_auth_conn_timeout: '5'
anchore_auth_max_retries: '3'
anchore_client_url: 'https://ancho.re/v1/account/users'
anchore_token_url: 'https://ancho.re/oauth/token'

feeds_url: 'https://ancho.re/v1/service/feeds'
feeds_conn_timeout: '10'
feeds_max_retries: '3'

